### ISSUE TITLE
wp-testing / pls give me your contact

### ISSUE THREAD

**Issue by garex** [osfans/trime-legacy#3]
Hi! Pls remove this issue when you receive notification about it.

I need some of your contact (not for publish) to send you updates about plugin/translations.

Will be great if you send me it to a@ustimen.co

**Comment by osfans** [comment]
I've received  email notification from transifex. But I find no new strings

**Comment by garex** [comment]
See

https://www.transifex.com/projects/p/wp-testing/translate/#zh_CN/wp-testing/44997002?tags=release011

Or

https://www.transifex.com/projects/p/wp-testing/translate/#zh_CN/wp-testing/44997002?reviewed=no

---

Alexander Ustimenko
    +7 (952) 918-02-20

2015-04-09 11:30 GMT+06:00 Osfans notifications@github.com:

**Comment by osfans** [comment]
Hi Alexander,
       
      I changed one of the two new translations, but I cannot review it.

**Comment by garex** [comment]
Ok, I'll review all of them now.

__________________
Alexander Ustimenko
    +7 (952) 918-02-20

2015-04-09 11:40 GMT+06:00 Osfans <notifications@github.com>:

**Comment by garex** [comment]
Hi!

Can you help me with registration on http://sae.sina.com.cn/ ?

Currently I stopped at the "Bad phone format". I think it wants local phone number.

I want to fix this issue: https://wordpress.org/support/topic/the-plugin-not-work?replies=10

And source error is "13019  Invalid operate information_schema" described at https://sae.sina.com.cn/doc/php/mysql.html

![image](https://cloud.githubusercontent.com/assets/77981/8248175/30a558be-1675-11e5-9fe6-9e19799a42d0.png)
